security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
#        in_memory: { memory: ~ }
        rest_user_provider:
            id: App\Security\Providers\RestUserProvider
    encoders:
        App\Security\Users\RestUser:
            algorithm: bcrypt
            cost: 12        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - App\Security\Authenticators\RestAuthenticator            
    access_control:
        - { path: ^/troubleticket, roles: ROLE_REST_USER }
            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
