post_service:
    path: /
    controller: 'App\Controller\Comercial\ServiceController::postService'
    methods: [POST]
    defaults:
        _format: json
        
get_service:
    path: /{id}
    controller: 'App\Controller\Comercial\ServiceController::getService'
    methods: [GET]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        
list_service:
    path: /
    controller: 'App\Controller\Comercial\ServiceController::getServices'
    methods: [GET]
    defaults:
        _format: json
        
delete_service:
    path: /{id}
    controller: 'App\Controller\Comercial\ServiceController::deleteService'
    methods: [DELETE]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        
put_service:
    path: /{id}
    controller: 'App\Controller\Comercial\ServiceController::putService'
    methods: [PUT]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        
patch_service:
    path: /{id}
    controller: 'App\Controller\Comercial\ServiceController::patchService'
    methods: [PATCH]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        