service:
    prefix: /services
    resource: './service/routes.yaml'

tag:
    prefix: /tags
    resource: './tag/routes.yaml'

prospect:
    prefix: /prospects
    resource: './prospect/routes.yaml'

wallet:
    prefix: /wallets
    resource: './wallet/routes.yaml'

chance:
    prefix: /chances
    resource: './chance/routes.yaml'

viable:
    prefix: /viables
    resource: './viable/routes.yaml'
    