#index:
#    path: /
#    controller: App\Controller\DefaultController::index
troubleticket:
    prefix: /troubleticket
    resource: './routes/troubleticket/routes.yaml'
comercial:
    prefix: /comercial
    resource: './routes/comercial/routes.yaml'
    