troubleticket:
    roles: [ROLE_USER]
    href: '#'
    text: TroubleTicket
    children: {  }
comercial:
    roles: [ROLE_USER]
    href: '/comercial'
    text: Comercial
    children: {  }
engenharia:
    roles: [ROLE_USER]
    href: '#'
    text: Engenharia
    children: {  }
prevendas:
    roles: [ROLE_USER]
    href: '#'
    text: Prevendas
    children: {  }
autorizacao:
    roles: [ROLE_USER]
    href: '#'
    text: Autorizacao
    children: {  }
    
pessoa:
    roles: [PESSOAS_VIEW, PESSOAS_INSERT, PESSOAS_EDIT, PESSOAS_DELETE]
    href: '#'
    text: Pessoa
    children:
        juridica:
            roles: [PESSOAS_VIEW, PESSOAS_INSERT, PESSOAS_EDIT, PESSOAS_DELETE]
            href: '#'
            text: "Jurídica"
            children: {  }
        fisica:
            roles: [PESSOAS_VIEW, PESSOAS_INSERT, PESSOAS_EDIT, PESSOAS_DELETE]
            href: '#'
            text: "Física"
            children: {  }
        