post_chance:
    path: /
    controller: 'App\Controller\Comercial\ChanceController::postChance'
    methods: [POST]
    defaults:
        _format: json
        
get_chance:
    path: /{id}
    controller: 'App\Controller\Comercial\ChanceController::getChance'
    methods: [GET]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        
list_chance:
    path: /
    controller: 'App\Controller\Comercial\ChanceController::getChances'
    methods: [GET]
    defaults:
        _format: json
        
delete_chance:
    path: /{id}
    controller: 'App\Controller\Comercial\ChanceController::deleteChance'
    methods: [DELETE]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        
put_chance:
    path: /{id}
    controller: 'App\Controller\Comercial\ChanceController::putChance'
    methods: [PUT]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        
put_chance_lost:
    path: /{id}/lost
    controller: 'App\Controller\Comercial\ChanceController::putChanceLost'
    methods: [PUT]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        
put_chance_inactive:
    path: /{id}/inactive
    controller: 'App\Controller\Comercial\ChanceController::putChanceInactive'
    methods: [PUT]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        
patch_chance:
    path: /{id}
    controller: 'App\Controller\Comercial\ChanceController::patchChance'
    methods: [PATCH]
    defaults:
        _format: json
    requirements:
        id: '\d+'
        