App\Entity\Autorizacao\Regras:
    type: entity
    table: autorizacao.regras
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nome:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    manyToMany:
        idUsuarios:
            targetEntity: App\Entity\Autorizacao\Usuarios
            cascade: {  }
            fetch: LAZY
            mappedBy: idRegras
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
