App\Entity\Comercial\LostChance:
    type: entity
    table: comercial.lost_chance
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        chanceId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: chance_id
        lostActionId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: lost_action_id
        dateRecord:
            type: datetime
            nullable: true
            options:
                default: now()
            column: date_record
        walletId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: wallet
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        chance:
            targetEntity: App\Entity\Comercial\Chance
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                chance_id:
                    referencedColumnName: id
            orphanRemoval: false
        wallet:
            targetEntity: App\Entity\Comercial\Wallet
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                wallet:
                    referencedColumnName: id
            orphanRemoval: false
        lostAction:
            targetEntity: App\Entity\Comercial\LostAction
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                lost_action_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
