App\Entity\Comercial\ChanceInactive:
    type: entity
    table: comercial.chance_inactive
    indexes:
        fki_chance_inactive_chance_id_fkey:
            columns:
                - chance_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        chanceId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: chance_id
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        recordDate:
            type: datetime
            nullable: true
            options:
                default: now()
            column: record_date
        active:
            type: boolean
            nullable: true
            options:
                default: true
    manyToOne:
        chance:
            targetEntity: App\Entity\Comercial\Chance
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                chance_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
