App\Entity\Comercial\ProposalNumber:
    type: entity
    table: comercial.proposal_number
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        proposalId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: proposal_id
        numberType:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: number_type
        quantity:
            type: integer
            nullable: true
            options:
                unsigned: false
        activationFare:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
            column: activation_fare
        monthlyCost:
            type: decimal
            nullable: true
            precision: 10
            scale: 0
            column: monthly_cost
    lifecycleCallbacks: {  }
