App\Entity\Comercial\FollowupAction:
    type: entity
    table: comercial.followup_action
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        subacao:
            type: boolean
            nullable: true
            options:
                default: true
        parentId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: parent_id
        visivel:
            type: boolean
            nullable: true
            options:
                default: true
    lifecycleCallbacks: {  }
