App\Entity\Comercial\Vip:
    type: entity
    table: comercial.vip
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        userId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_id
        dateRecord:
            type: datetime
            nullable: true
            options:
                default: now()
            column: date_record
        active:
            type: boolean
            nullable: true
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        levelId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: level_id
    lifecycleCallbacks: {  }
