App\Entity\Comercial\ProposalProtocolHistoric:
    type: entity
    table: comercial.proposal_protocol_historic
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        dateInc:
            type: datetime
            nullable: false
            column: date_inc
        proposalProtocolId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: proposal_protocol_id
        autUsuariosId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: aut_usuarios_id
        department:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        proposalProtocolStatusId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: proposal_protocol_status_id
        reasonDenial:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
            column: reason_denial
        contractDenialReasonId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: contract_denial_reason_id
    lifecycleCallbacks: {  }
