App\Entity\Comercial\ContractDenialReasonCategory:
    type: entity
    table: comercial.contract_denial_reason_category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 80
            options:
                fixed: false
    lifecycleCallbacks: {  }
