App\Entity\Comercial\GlobalAddress:
    type: entity
    table: comercial.global_address
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 2044
            options:
                fixed: false
        cep:
            type: string
            nullable: false
            length: 2044
            options:
                fixed: false
        city:
            type: integer
            nullable: false
            options:
                unsigned: false
        complement:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        dateRecord:
            type: datetime
            nullable: false
            column: date_record
        district:
            type: string
            nullable: false
            length: 2044
            options:
                fixed: false
        lat:
            type: string
            nullable: false
            length: 2044
            options:
                fixed: false
        lon:
            type: string
            nullable: false
            length: 2044
            options:
                fixed: false
        street:
            type: string
            nullable: false
            length: 2044
            options:
                fixed: false
        uf:
            type: string
            nullable: false
            length: 2044
            options:
                fixed: false
        active:
            type: boolean
            nullable: false
        number:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
