App\Entity\Comercial\Tag:
    type: entity
    table: comercial.tag
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        color:
            type: string
            nullable: false
            length: 7
            options:
                fixed: false
        status:
            type: boolean
            nullable: false
            options:
                default: true
    lifecycleCallbacks: {  }
