App\Entity\Engenharia\Type:
    type: entity
    table: engenharia.type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: true
    lifecycleCallbacks: {  }
