App\Entity\Prevendas\Region:
    type: entity
    table: prevendas.region
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        max:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
