App\Entity\Prevendas\Lpu:
    type: entity
    table: prevendas.lpu
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        serviceId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: service_id
        author:
            type: integer
            nullable: false
            options:
                unsigned: false
        dateRecord:
            type: datetime
            nullable: false
            column: date_record
            options:
                default: now()
        dateValid:
            type: datetime
            nullable: true
            column: date_valid
        distance:
            type: integer
            nullable: true
            options:
                unsigned: false
        active:
            type: boolean
            nullable: false
            options:
                default: true
        minContractDeadline:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '12'
            column: min_contract_deadline
        minContractUnit:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '1'
            column: min_contract_unit
        sla:
            type: decimal
            nullable: true
            precision: 5
            scale: 2
        modeCodigoid:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: mode_codigoid
        minimumPrice:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
            column: minimum_price
        onlineSales:
            type: boolean
            nullable: false
            column: online_sales
            options:
                default: false
        type:
            type: string
            nullable: false
            length: 1
            options:
                fixed: false
                default: P
    lifecycleCallbacks: {  }
