App\Entity\Prevendas\FeatureAttribute:
    type: entity
    table: prevendas.feature_attribute
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        featureId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: feature_id
        defaultSelected:
            type: boolean
            nullable: false
            options:
                default: false
            column: default_selected
        active:
            type: boolean
            nullable: false
            options:
                default: true
    lifecycleCallbacks: {  }
