App\Entity\Prevendas\LpuFeature:
    type: entity
    table: prevendas.lpu_feature
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        activationFare:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: activation_fare
        monthlyCost:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: monthly_cost
        dateRecord:
            type: datetime
            nullable: true
            column: date_record
        lpuId:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: lpu_id
        dateValid:
            type: datetime
            nullable: true
            column: date_valid
        featureAttributeId:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: feature_attribute_id
        quantity:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
