App\Entity\Prevendas\NumberType:
    type: entity
    table: prevendas.number_type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
