App\Entity\Prevendas\Service:
    type: entity
    table: prevendas.service
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        servCodigoid:
            type: bigint
            nullable: true
            options:
                unsigned: false
            column: serv_codigoid
        active:
            type: boolean
            nullable: true
            options:
                default: true
        quotable:
            type: boolean
            nullable: false
            options:
                default: false
    lifecycleCallbacks: {  }
